services:
  - type: web
    name: langgraph-agentic-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app_streamlit.py --server.port $PORT --server.enableCORS false
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_API_BASE
        value: https://openrouter.ai/api/v1
